steps:
  - name: docker
    args: ['compose', 'up']
  - name: 'docker'
    args: ['tag',
      'my-app',
      '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/my-app:$COMMIT_SHA']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'monorepo-my-app', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/my-app:$COMMIT_SHA', '--region', '$LOCATION']
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/my-app:$COMMIT_SHA'